name: EB_3263
channels:
  - conda-forge
  - defaults
dependencies:
  - control
  - matplotlib
  - numpy
  - sympy
  - python=3.10.*
  - oct2py
  - oauth2client
  - gspread
  - pip:
    - cbor
    - cryptocode
    - pyzmq
